### ISSUE TITLE
Dynamic compounds not generated in grammarchecker

### ISSUE THREAD

**Issue by Trondtr** [giellalt/lang-smn#5]
Overview: The grc uses `generator-gramcheck-gt-norm.hfstol`, which does not generate compounds. The ordinary generator handles compounds, but is not used in the grammarchecker. (this bug moved from #68 in github.com/divvun/gramcheck-web

```
correct fst, wrong result:
uit-mac-443:grammarcheckers ttr000$ e muotâ+N+Cmp/SgNom+Cmp#sääni+v1+N+Pl+Nom|hfst-lookup -q ../../src/generator-gramcheck-gt-norm.hfstol 
muotâ+N+Cmp/SgNom+Cmp#sääni+v1+N+Pl+Nom	muotâ+N+Cmp/SgNom+Cmp#sääni+v1+N+Pl+Nom+?	inf

wrong fst, correct result:
uit-mac-443:grammarcheckers ttr000$ e muotâ+N+Cmp/SgNom+Cmp#sääni+v1+N+Pl+Nom|hfst-lookup -q ../../src/generator-gt-norm.hfstol 
muotâ+N+Cmp/SgNom+Cmp#sääni+v1+N+Pl+Nom	muotâsäänih	0,000000
```

**Comment by Trondtr** [comment]
Sjur comments:

The way I usually debug missing generator issues is to use the fst upside down, with the utility hfst-flookup. You then input the word form you expect to be generated, and in return you get the analysis that will generate it. Then compare lemmas and tags, and see if there are differences. Usually there are.

NB! hfst-flookup does not handle the optimised lookup format, so if needed reconvert to the standard Hfst format.

**Comment by Trondtr** [comment]
The hfst-flookup debugging gives:

```
uit-mac-443:grammarcheckers ttr000$ e muotâsäänih|hfst-flookup ../../src/generator-gramcheck-gt-norm.hfst
hfst-flookup: warning: It is not possible to perform fast lookups with foma format automata.
Using HFST basic transducer format and performing slow lookups
> muotâsäänih	muotâ+N+Sem/Substnc_Wthr+Cmp#sääni+v1+N+Sem/Cat+Pl+Nom	0,000000
muotâsäänih	muotâ+N+Sem/Substnc_Wthr+Cmp#sääni+v1+N+Pl+Nom	0,000000
muotâsäänih	muotâ+N+Sem/Substnc_Wthr+Cmp#sääni+N+Sem/Cat+Pl+Nom	0,000000
muotâsäänih	muotâ+N+Sem/Substnc_Wthr+Cmp#sääni+N+Pl+Nom	0,000000
muotâsäänih	muotâ+N+Cmp#sääni+v1+N+Sem/Cat+Pl+Nom	0,000000
muotâsäänih	muotâ+N+Cmp#sääni+v1+N+Pl+Nom	0,000000
muotâsäänih	muotâ+N+Cmp#sääni+N+Sem/Cat+Pl+Nom	0,000000
muotâsäänih	muotâ+N+Cmp#sääni+N+Pl+Nom	0,000000
```

There is a difference between the tagstrings: `+Cmp/SgNom` is given in the grc input to the generator, but not offered in the flookup analysis.

To me, this does not seem like a smn specific issue.

**Comment by snomos** [comment]
The output shows what I suspected: a tag mismatch between what the generator gets and what it expects - the analysis output is what you need to use as input to be able to generate.

`+Cmp/SgNom` is a descriptive, compounding tag, and these are removed from all normative generators (one could consider making them optional). By removing such tags in a late CG rule, the issue should be solved. The rule should be late, as descriptive compounding tags can be used to identify errors (ie a mismatch between a descriptive and a normative compounding tag), and such error identification needs to happen first.

Compounding tags are pr definition language specific, since many languages do not have compounds, at least not in a productive way.

**Comment by albbas** [comment]
For sme, the same kind of query works:
```
❯ echo muohtasánit | hfst-lookup -q /usr/share/giella/sme/analyser-gramcheck-gt-desc.hfstol 
muohtasánit     muohta+N+Sem/Substnc_Wthr+Cmp/SgNom+Cmp#sátni+N+Sem/Cat+Pl+Nom  0,000000
muohtasánit     muohtasátni+N+Sem/Cat+Pl+Nom    0,000000

❯ echo muohta+N+Sem/Substnc_Wthr+Cmp/SgNom+Cmp#sátni+N+Sem/Cat+Pl+Nom|hfst-lookup -q /usr/share/giella/sme/
muohta+N+Sem/Substnc_Wthr+Cmp/SgNom+Cmp#sátni+N+Sem/Cat+Pl+Nom  muohtasánit     0,000000
```
So, the smn compilation process when making `generator-gramcheck-gt-norm.hfstol` seems to be stricter than the sme one.

**Comment by Trondtr** [comment]
sme does not have a cg rule for removing +Cmp/SgNom. Thus, it seems it is removed from `generator-gramcheck-gt-norm.hfstol` via a filter somewhere. Should we do the same for smn? Removing the tags in cg is easy, but well, hmm.

**Comment by Trondtr** [comment]
To follow up Sjurs suggestion, I now remove the Cmp/SgNom and Cmp/SgGen tags finally in the grc-disambiguator.cg3 file, cf. https://github.com/giellalt/lang-smn/commit/3540434edbfafc6602371fc283d0d21f2e70d189. This gives the intended result: The compound is now generated.
